// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxaletskzrvaugifpfak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14YWxldHNrenJ2YXVnaWZwZmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDE1NzQsImV4cCI6MjA2NTM3NzU3NH0.xf5mFzDJCueDkd1YM0OXn0NBX5Xw8JhklhBaEsyVkRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);